# Experiment selection
experiment:
  name: "bayesian_optimization" # toy_data_experiments, uci_regression, image_regression, ood_detection_regression, bandits, hpo_regression
  # hpo_classification, ood_detection_classification, experiments_classification
  sweep_id: ""

# Model selection
model:
  name: "GP" # FSPLaplace, SNGP, GP, GWI, SamplingLaplace, Laplace


# Model configuration 
gp:
  n_inducing_pts: 100 # use a max of 1000 inducing points for the GP model

  posterior:
    type: "GP" # GP, SVGP
    n_inducing_pts: 10

  likelihood:
    model: "Gaussian" # Gaussian, Categorical
    scale: 1.
    n_classes: 2

  # Prior 
  prior:
    kernel: "Matern52" # RBF, Matern12, Matern32, Matern52, Linear, RationalQuadratic, PoweredExponential
    params:  #{lengthscale: 1., variance: 1., alpha: 1.}

  # Training configuration
  training:
    nb_epochs: 1000
    lr: 0.005
    validation_freq: 100
    early_stopping_patience: 50
    save_model: false
    model_path: 


bayes_opt:
  name: "bnn_10_1" #  pde, lunar, pest, optics, kd, bnn, poly
  n_trials: 5
  n_init_points: 10
  n_BO_iters: 20
  batch_size: 10
  start_trial: 0 #  launch 4th trial
  
# Dataset configuration 
data:
  name: "" 
  # ToyData: truncated_sine, two_moons
  # UCI: boston, concrete, energy, kin8nm, naval, power, protein, wine, yacht, wave
  # Image: mnist, fashion_mnist, cifar10, svhn
  feature_dim: 1
  n_samples: 300
  batch_size: 1000
  k_folds: 1