# Experiment selection
experiment:
  name: "bayesian_optimization" # toy_data_experiments, uci_regression, image_regression, ood_detection_regression, bandits, hpo_regression
  # hpo_classification, ood_detection_classification, experiments_classification
  sweep_id: ""

# Model selection
model:
  name: "FSPLaplace" # FSPLaplace, SNGP, GP, GWI, SamplingLaplace, Laplace

# Model configuration  
fsplaplace:
  neural_net:
    type: "MLP" # MLP, CNN1, CNN2
    architecture: [50, 50]
    activation_fn: "tanh"
    validation_freq: 10
    periodic_features: 

  inference:
    n_chunks: 100 # needs to divide the number of context points
    max_rank: 500
    cov_type: "low_rank_lanczos" # low_rank, diag, low_rank_sketch, low_rank_lanczos
    cov_context_selection: "latin_hypercube" # grid, latin_hypercube, train_val_latin, song, halton
    n_context_points: 10000 # needs to divide 50
    max_posterior_precision: 1.e-15 #0.1 # tuned by cross-validation
    save_covariance: false
    covariance_path: ""

  likelihood:
    model: "Gaussian" # Gaussian, Categorical
    scale: 1.0
    n_classes: 2

  training:
    mc_samples: 10
    nb_epochs: 10000
    lr: 0.005
    patience: 50
    n_context_points: 400
    context_selection: "random" # random, grid
    save_weights: false
    pretrained_weights_path: ""

  prior:
    kernel: "Matern52" # RBF, Matern12, Matern32, Matern52, Linear, Periodic, RationalQuadratic, Cauchy
    parameter_tuning: true
    nb_epochs: 1000
    batch_size: 100
    alpha_eps: 0.001 # recommended
    lr: 0.05
    parameters: {"lengthscale": 0.25, "variance": 0.5, "alpha": 4.3} 


bayes_opt:
  name: "poly_8" #  pde, lunar, pest, optics, kd, bnn, poly
  n_trials: 5
  n_init_points: 10
  n_BO_iters: 20
  batch_size: 10
  start_trial: 3 #  launch 4th trial

# Dataset configuration 
data:
  name: "" 
  # ToyData: truncated_sine, two_moons
  # UCI: boston, concrete, energy, kin8nm, naval, power, protein, wine, yacht, wave
  # Image: mnist, fashion_mnist, cifar10, svhn
  feature_dim: 1
  n_samples: 300
  batch_size: 1000
  k_folds: 1